# Generated by Django 4.0.3 on 2022-03-30 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Post name')),
                ('link', models.URLField(verbose_name='Post link')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('upvotes', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=50, verbose_name='Author name')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author name')),
                ('content', models.TextField(max_length=1000, verbose_name='Comment content')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coment', to='project.post')),
            ],
            options={
                'verbose_name': 'Coment',
                'verbose_name_plural': 'Coments',
            },
        ),
    ]
